-- Inserindo os 2 tipos fixos de acabamento conforme o enum TipoAcabamento
INSERT INTO ACABAMENTO (ID, TIPO_ACABAMENTO) VALUES (1, 'CAPA_DURA');
INSERT INTO ACABAMENTO (ID, TIPO_ACABAMENTO) VALUES (2, 'BROCHURA');


INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Ficção');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Não-ficção');


-- Inserindo os 4 tipos fixos de conservação conforme o enum TipoConservacao
INSERT INTO CONSERVACAO (ID, TIPO_CONSERVACAO) VALUES (1, 'EXCELENTE');
INSERT INTO CONSERVACAO (ID, TIPO_CONSERVACAO) VALUES (2, 'BOM');
INSERT INTO CONSERVACAO (ID, TIPO_CONSERVACAO) VALUES (3, 'RAZOAVEL');
INSERT INTO CONSERVACAO (ID, TIPO_CONSERVACAO) VALUES (4, 'DEGRADADO');
